### ISSUE TITLE
On KDE + wayland, chromium lacks font antialiasing

### ISSUE THREAD

**Issue by alxpettit** [nixpak/pkgs#1]
No obvious error messages as to why in stdout/stderr. Problem does not occur on flatpak release of chromium (org.chromium.Chromium). However, it does seem to turn up a lot on flatpak GNOME apps on Wayland.

![image](https://github.com/nixpak/pkgs/assets/28266167/b050be99-a640-462e-9d3b-8a62299f6d14)

![image](https://github.com/nixpak/pkgs/assets/28266167/0a8d72e3-3663-4790-8504-226c515d14ff)

**Comment by Guanran928** [comment]
I believe it is a known issue with Flatpak already.
https://github.com/flatpak/flatpak/issues/2861

Do you have XDG portals installed? If no, try installing them.

**Comment by alxpettit** [comment]
I _think_ I have solved this issue, but I can't even get `chromium` via nixpak to run nowadays to check, sadly.

**Comment by alxpettit** [comment]
I'll close this issue for now and re-open if I can replicate my own issue in the future. :P
